includes:
  - configs/_base/general.yaml
  - configs/_base/logging.yaml
  - configs/_base/optim.yaml
  - configs/_base/loss.yaml
  - configs/_base/datasets/scannetpp.yaml
  - configs/_base/model/vggt.yaml
  - configs/_base/model/clip_teacher.yaml
  - configs/_base/model/lifter.yaml
  - configs/_base/model/projector.yaml
