includes:
  - configs/base/general.yaml
  - configs/base/logging.yaml
  - configs/base/optim.yaml
  - configs/base/loss.yaml
  - configs/base/datasets/scannetpp.yaml
  - configs/base/model/vggt.yaml
  - configs/base/model/clip_teacher.yaml
  - configs/base/model/lifter.yaml
  - configs/base/model/projector.yaml
